[[redirects]]

    from = "/"
    to = "https://medium.com/reflections-on-building-software"
    status = 302
    force = true

[[redirects]]

    from = "/feed"
    to = "https://medium.com/feed/reflections-on-building-software/"
    status = 302
    force = true

[[redirects]]

    from = "/context-menus-and-the-design-of-design"
    to = "https://medium.com/reflections-on-building-software/context-menus-and-the-design-of-design-2d656ebbf633"
    status = 302
    force = true

[[redirects]]

    from = "/determining-whether-users-are-logged-into-twitter"
    to = "https://medium.com/reflections-on-building-software/determining-whether-users-are-logged-into-twitter-21c0638339a7"
    status = 302
    force = true

[[redirects]]

    from = "/using-the-optimizely-api-to-avoid-flashes-of-unstyled-content-in-ab-tests"
    to = "https://medium.com/reflections-on-building-software/using-the-optimizely-api-to-avoid-flashes-of-unstyled-content-in-a-b-tests-32c314c14caa"
    status = 302
    force = true

[[redirects]]

    from = "/less-is-more"
    to = "https://medium.com/reflections-on-building-software/less-is-more-ec1c40534826"
    status = 302
    force = true

[[redirects]]

    from = "/when-a-readme-accidentally-becomes-a-manifesto"
    to = "https://medium.com/reflections-on-building-software/when-a-readme-accidentally-becomes-a-manifesto-9b5f571b4c8d"
    status = 302
    force = true

# Everything else
[[redirects]]

    from = "/*"
    to = "https://medium.com/reflections-on-building-software"
    status = 302
    force = true
